import { Config } from "./types";

const config: Config = {
	AUTHORIZATION_DOMAIN:
		process?.env?.NEXT_PUBLIC_AUTHORIZATION_DOMAIN || "#{AUTHORIZATION_DOMAIN}",
	AUTHORIZATION_CLIENT_ID:
		process?.env?.NEXT_PUBLIC_AUTHORIZATION_CLIENT_ID ||
		"#{AUTHORIZATION_CLIENT_ID}",
	GRAPHQL_CLIENT_URI:
		process?.env?.NEXT_PUBLIC_GRAPHQL_CLIENT_URI || "#{GRAPHQL_CLIENT_URI}",
	GRAPHQL_USER_PROFILE_URI:
		process?.env?.NEXT_PUBLIC_GRAPHQL_USER_PROFILE_URI ||
		"#{GRAPHQL_USER_PROFILE_URI}",
	AUTHORIZATION_AUDIENCE:
		process?.env?.NEXT_PUBLIC_AUTHORIZATION_AUDIENCE ||
		"#{AUTHORIZATION_AUDIENCE}",
	GRAPHQL_MESH_URI:
		process?.env?.NEXT_PUBLIC_GRAPHQL_MESH_URI || "#{GRAPHQL_MESH_URI}",
};

export default config;
