export interface Config {
	AUTHORIZATION_DOMAIN: string;
	AUTHORIZATION_CLIENT_ID: string;
	GRAPHQL_CLIENT_URI: string;
	GRAPHQL_USER_PROFILE_URI: string;
	AUTHORIZATION_AUDIENCE: string;
	GRAPHQL_MESH_URI: string;
}
